-- Generated by `rti-build-db`. Do not edit; edit src/rti/enums.py instead.
--
-- Three tables. `authority` is the office, `application` is one planned letter,
-- `event` is one thing that happened to it. Everything else a study needs --
-- days to response, current status, transfer count, whether a reply is overdue
-- -- is derived in the views below rather than stored, so nothing can go stale.
--
-- An `application` row is created when the office is SAMPLED, not when the
-- letter is filed. `filing_outcome` distinguishes the three real states:
-- blank (nobody has reported yet), 'filed', and 'not_filed' with a reason.
-- That is what makes the study's attrition visible months later.

PRAGMA foreign_keys = ON;


DROP TABLE IF EXISTS authority;
CREATE TABLE authority (
    authority_id             TEXT PRIMARY KEY,
    state                    TEXT,
    state_code               TEXT,
    department               TEXT,
    district                 TEXT,
    block                    TEXT,
    portal                   TEXT,
    relevant                 INTEGER,
    category                 TEXT,
    first_sampled_batch      TEXT
);

DROP TABLE IF EXISTS application;
CREATE TABLE application (
    application_id           TEXT PRIMARY KEY,
    batch_id                 TEXT,
    authority_id             TEXT,
    state                    TEXT,
    department               TEXT,
    topic                    TEXT CHECK (topic = '' OR topic IN ('rti_meta', 'attendance', 'financial')),
    language                 TEXT CHECK (language = '' OR language IN ('en', 'hi', 'ta', 'te', 'kn', 'mr')),
    channel                  TEXT CHECK (channel = '' OR channel IN ('portal', 'post')),
    template_version         TEXT,
    filing_outcome           TEXT CHECK (filing_outcome = '' OR filing_outcome IN ('filed', 'not_filed')),
    not_filed_reason         TEXT CHECK (not_filed_reason = '' OR not_filed_reason IN ('authority_not_listed', 'portal_down', 'login_failed', 'otp_not_received', 'captcha_failed', 'payment_failed', 'authority_abolished', 'address_invalid', 'duplicate_of_other_application', 'dropped_by_design', 'other')),
    filing_date              TEXT,
    registration_number      TEXT,
    fee_paid_inr             INTEGER,
    payment_mode             TEXT CHECK (payment_mode = '' OR payment_mode IN ('online', 'ipo', 'dd', 'court_fee_stamp', 'cash', 'bpl_exempt', 'not_paid')),
    payment_reference        TEXT,
    evidence_url             TEXT,
    screen_recording_url     TEXT,
    due_date                 TEXT,
    filed_by                 TEXT,
    notes                    TEXT,
    source_row_id            TEXT,
    FOREIGN KEY (authority_id) REFERENCES authority(authority_id)
);

DROP TABLE IF EXISTS event;
CREATE TABLE event (
    event_id                 TEXT PRIMARY KEY,
    application_id           TEXT,
    event_date               TEXT,
    event_type               TEXT CHECK (event_type = '' OR event_type IN ('acknowledgment', 'transfer_6_3', 'fee_demand', 'clarification_demand', 'id_demand', 'personal_contact', 'interim_reply', 'response_received', 'denial', 'returned_undelivered', 'reminder_sent', 'first_appeal_filed', 'first_appeal_decided', 'second_appeal_filed', 'hearing_notice', 'second_appeal_decided', 'note')),
    direction                TEXT CHECK (direction = '' OR direction IN ('inbound', 'outbound')),
    medium                   TEXT CHECK (medium = '' OR medium IN ('portal', 'email', 'post', 'speed_post', 'phone', 'in_person')),
    actor_authority          TEXT,
    document_url             TEXT,
    notes                    TEXT,
    recorded_by              TEXT,
    recorded_at              TEXT,
    source_row_id            TEXT,
    FOREIGN KEY (application_id) REFERENCES application(application_id)
);

CREATE INDEX idx_event_application ON event(application_id);
CREATE INDEX idx_event_type        ON event(event_type);
CREATE INDEX idx_application_batch ON application(batch_id);

-- One row per application, with the study's outcome measures derived.
DROP VIEW IF EXISTS v_status;
CREATE VIEW v_status AS
SELECT
    a.application_id,
    a.batch_id,
    a.state,
    a.department,
    a.topic,
    a.language,
    a.filing_outcome,
    a.not_filed_reason,
    a.filing_date,
    a.due_date,
    (SELECT e.event_date FROM event e
      WHERE e.application_id = a.application_id AND e.event_type = 'acknowledgment'
      ORDER BY e.event_date LIMIT 1)                              AS first_ack_date,
    (SELECT e.event_date FROM event e
      WHERE e.application_id = a.application_id AND e.event_type = 'response_received'
      ORDER BY e.event_date LIMIT 1)                              AS response_date,
    (SELECT COUNT(*) FROM event e
      WHERE e.application_id = a.application_id AND e.event_type = 'transfer_6_3')
                                                                  AS n_transfers,
    (SELECT COUNT(*) FROM event e
      WHERE e.application_id = a.application_id AND e.event_type = 'fee_demand')
                                                                  AS n_fee_demands,
    (SELECT e.event_type FROM event e
      WHERE e.application_id = a.application_id
      ORDER BY e.event_date DESC, e.event_id DESC LIMIT 1)        AS last_event,
    (SELECT MAX(e.event_date) FROM event e
      WHERE e.application_id = a.application_id)                  AS last_event_date,
    CASE
        WHEN a.filing_outcome = 'not_filed' THEN 'not filed'
        WHEN a.filing_outcome = ''          THEN 'not yet reported'
        WHEN EXISTS (SELECT 1 FROM event e WHERE e.application_id = a.application_id
                     AND e.event_type = 'response_received')            THEN 'replied'
        WHEN EXISTS (SELECT 1 FROM event e WHERE e.application_id = a.application_id
                     AND e.event_type = 'denial')                       THEN 'refused'
        WHEN a.due_date <> '' AND DATE(a.due_date) < DATE('now')         THEN 'overdue'
        ELSE 'awaiting reply'
    END                                                           AS status,
    CAST(julianday(
        (SELECT e.event_date FROM event e
          WHERE e.application_id = a.application_id AND e.event_type = 'response_received'
          ORDER BY e.event_date LIMIT 1)
    ) - julianday(NULLIF(a.filing_date, '')) AS INTEGER)          AS days_to_response
FROM application a;

-- The denominator, one row per state: sampled, filed, and what stopped the rest.
DROP VIEW IF EXISTS v_attrition;
CREATE VIEW v_attrition AS
SELECT
    state,
    COUNT(*)                                                        AS sampled,
    SUM(filing_outcome = 'filed')                                   AS filed,
    SUM(filing_outcome = 'not_filed')                               AS not_filed,
    SUM(filing_outcome = '')                                        AS not_yet_reported,
    SUM(not_filed_reason = 'authority_not_listed')                  AS not_listed_on_portal,
    SUM(not_filed_reason = 'payment_failed')                        AS payment_failed
FROM application
GROUP BY state
ORDER BY state;
