"""Generate the schema and rebuild the database from the committed CSVs.

`rti.db` is derived. Nothing writes to it except this command, and it is
gitignored, so it cannot drift away from `data/tables/*.csv`. If it is ever
wrong, delete it and rebuild.

The DDL is generated from `enums.py` and `tables.py` rather than maintained by
hand, so a new event type becomes a legal value in SQL, an option in the Google
Form, and an accepted value in the validator at the same moment.
"""

from __future__ import annotations

import argparse
import sqlite3
from pathlib import Path

from .config import db_path, repo_root
from .enums import (
    CHANNELS,
    DIRECTIONS,
    EVENT_TYPES,
    FILING_OUTCOMES,
    LANGUAGES,
    MEDIUMS,
    NOT_FILED_REASONS,
    PAYMENT_MODES,
    TOPICS,
    sql_check,
)
from .tables import TABLES, read_table

HEADER = """\
-- Generated by `rti-build-db`. Do not edit; edit src/rti/enums.py instead.
--
-- Three tables. `authority` is the office, `application` is one planned letter,
-- `event` is one thing that happened to it. Everything else a study needs --
-- days to response, current status, transfer count, whether a reply is overdue
-- -- is derived in the views below rather than stored, so nothing can go stale.
--
-- An `application` row is created when the office is SAMPLED, not when the
-- letter is filed. `filing_outcome` distinguishes the three real states:
-- blank (nobody has reported yet), 'filed', and 'not_filed' with a reason.
-- That is what makes the study's attrition visible months later.

PRAGMA foreign_keys = ON;
"""


CONSTRAINED = {
    ("application", "topic"): TOPICS,
    ("application", "language"): LANGUAGES,
    ("application", "channel"): CHANNELS,
    ("application", "filing_outcome"): FILING_OUTCOMES,
    ("application", "not_filed_reason"): NOT_FILED_REASONS,
    ("application", "payment_mode"): PAYMENT_MODES,
    ("event", "event_type"): EVENT_TYPES,
    ("event", "direction"): DIRECTIONS,
    ("event", "medium"): MEDIUMS,
}

PRIMARY_KEYS = {"authority": "authority_id", "application": "application_id", "event": "event_id"}

INTEGER_COLUMNS = {("authority", "relevant"), ("application", "fee_paid_inr")}


def _column_sql(table: str, column: str) -> str:
    """One column definition, with a CHECK constraint where a vocabulary exists."""
    kind = "INTEGER" if (table, column) in INTEGER_COLUMNS else "TEXT"
    parts = [f"    {column:<24} {kind}"]
    if PRIMARY_KEYS[table] == column:
        parts.append("PRIMARY KEY")
    values = CONSTRAINED.get((table, column))
    if values:
        parts.append(sql_check(column, values))
    return " ".join(parts)


def ddl() -> str:
    """The whole schema, as text."""
    out = [HEADER]
    for table, columns in TABLES.items():
        lines = [_column_sql(table, c) for c in columns]
        if table == "application":
            lines.append("    FOREIGN KEY (authority_id) REFERENCES authority(authority_id)")
        if table == "event":
            lines.append("    FOREIGN KEY (application_id) REFERENCES application(application_id)")
        out.append(
            f"\nDROP TABLE IF EXISTS {table};\nCREATE TABLE {table} (\n"
            + ",\n".join(lines)
            + "\n);"
        )

    out.append("""
CREATE INDEX idx_event_application ON event(application_id);
CREATE INDEX idx_event_type        ON event(event_type);
CREATE INDEX idx_application_batch ON application(batch_id);

-- One row per application, with the study's outcome measures derived.
DROP VIEW IF EXISTS v_status;
CREATE VIEW v_status AS
SELECT
    a.application_id,
    a.batch_id,
    a.state,
    a.department,
    a.topic,
    a.language,
    a.filing_outcome,
    a.not_filed_reason,
    a.filing_date,
    a.due_date,
    (SELECT e.event_date FROM event e
      WHERE e.application_id = a.application_id AND e.event_type = 'acknowledgment'
      ORDER BY e.event_date LIMIT 1)                              AS first_ack_date,
    (SELECT e.event_date FROM event e
      WHERE e.application_id = a.application_id AND e.event_type = 'response_received'
      ORDER BY e.event_date LIMIT 1)                              AS response_date,
    (SELECT COUNT(*) FROM event e
      WHERE e.application_id = a.application_id AND e.event_type = 'transfer_6_3')
                                                                  AS n_transfers,
    (SELECT COUNT(*) FROM event e
      WHERE e.application_id = a.application_id AND e.event_type = 'fee_demand')
                                                                  AS n_fee_demands,
    (SELECT e.event_type FROM event e
      WHERE e.application_id = a.application_id
      ORDER BY e.event_date DESC, e.event_id DESC LIMIT 1)        AS last_event,
    (SELECT MAX(e.event_date) FROM event e
      WHERE e.application_id = a.application_id)                  AS last_event_date,
    CASE
        WHEN a.filing_outcome = 'not_filed' THEN 'not filed'
        WHEN a.filing_outcome = ''          THEN 'not yet reported'
        WHEN EXISTS (SELECT 1 FROM event e WHERE e.application_id = a.application_id
                     AND e.event_type = 'response_received')            THEN 'replied'
        WHEN EXISTS (SELECT 1 FROM event e WHERE e.application_id = a.application_id
                     AND e.event_type = 'denial')                       THEN 'refused'
        WHEN a.due_date <> '' AND DATE(a.due_date) < DATE('now')         THEN 'overdue'
        ELSE 'awaiting reply'
    END                                                           AS status,
    CAST(julianday(
        (SELECT e.event_date FROM event e
          WHERE e.application_id = a.application_id AND e.event_type = 'response_received'
          ORDER BY e.event_date LIMIT 1)
    ) - julianday(NULLIF(a.filing_date, '')) AS INTEGER)          AS days_to_response
FROM application a;

-- The denominator, one row per state: sampled, filed, and what stopped the rest.
DROP VIEW IF EXISTS v_attrition;
CREATE VIEW v_attrition AS
SELECT
    state,
    COUNT(*)                                                        AS sampled,
    SUM(filing_outcome = 'filed')                                   AS filed,
    SUM(filing_outcome = 'not_filed')                               AS not_filed,
    SUM(filing_outcome = '')                                        AS not_yet_reported,
    SUM(not_filed_reason = 'authority_not_listed')                  AS not_listed_on_portal,
    SUM(not_filed_reason = 'payment_failed')                        AS payment_failed
FROM application
GROUP BY state
ORDER BY state;
""")
    return "\n".join(out).rstrip() + "\n"


def build(target: Path | None = None) -> tuple[Path, dict[str, int]]:
    target = target or db_path()
    target.unlink(missing_ok=True)
    conn = sqlite3.connect(target)
    try:
        conn.executescript(ddl())
        counts = {}
        for table, columns in TABLES.items():
            rows = read_table(table)
            placeholders = ", ".join("?" for _ in columns)
            conn.executemany(
                f"INSERT INTO {table} ({', '.join(columns)}) VALUES ({placeholders})",
                [tuple(r.get(c, "") or "" for c in columns) for r in rows],
            )
            counts[table] = len(rows)
        conn.commit()
    finally:
        conn.close()
    return target, counts


def main(argv: list[str] | None = None) -> None:
    ap = argparse.ArgumentParser(description="Rebuild rti.db from data/tables/*.csv.")
    ap.add_argument("--out", type=Path, default=None, help="default: rti.db")
    ap.add_argument(
        "--schema-only",
        action="store_true",
        help="write schema.sql and stop, without touching the database",
    )
    args = ap.parse_args(argv)

    schema_path = repo_root() / "schema.sql"
    schema_path.write_text(ddl(), encoding="utf-8")
    print(f"schema -> {schema_path}")
    if args.schema_only:
        return

    target, counts = build(args.out)
    print(f"database -> {target}")
    for table, n in counts.items():
        print(f"  {table}: {n} rows")


if __name__ == "__main__":
    main()
